name: Run
on: workflow_dispatch

jobs:
  Bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Node.js
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run Discord bot
        timeout-minutes: 5
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: npm run start